src/Entity/Orders.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrdersRepository")
 */
class Orders
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $orderDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Address", mappedBy="orders")
     */
    private $deliveryAddress;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LineItem", mappedBy="orders")
     */
    private $lineItems;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="orders")
     */
    private $User;

    public function __construct()
    {
        $this->deliveryAddress = new ArrayCollection();
        $this->lineItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderDate(): ?\DateTime
    {
        return $this->orderDate;
    }

    public function setOrderDate(\DateTime $orderDate): self
    {
        $this->orderDate = $orderDate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getDeliveryAddress(): Collection
    {
        return $this->deliveryAddress;
    }

    public function addDeliveryAddress(Address $deliveryAddress): self
    {
        if (!$this->deliveryAddress->contains($deliveryAddress)) {
            $this->deliveryAddress[] = $deliveryAddress;
            $deliveryAddress->setOrders($this);
        }

        return $this;
    }

    public function removeDeliveryAddress(Address $deliveryAddress): self
    {
        if ($this->deliveryAddress->contains($deliveryAddress)) {
            $this->deliveryAddress->removeElement($deliveryAddress);
            // set the owning side to null (unless already changed)
            if ($deliveryAddress->getOrders() === $this) {
                $deliveryAddress->setOrders(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LineItem[]
     */
    public function getLineItems(): Collection
    {
        return $this->lineItems;
    }

    public function addLineItem(LineItem $lineItem): self
    {
        if (!$this->lineItems->contains($lineItem)) {
            $this->lineItems[] = $lineItem;
            $lineItem->setOrders($this);
        }

        return $this;
    }

    public function removeLineItem(LineItem $lineItem): self
    {
        if ($this->lineItems->contains($lineItem)) {
            $this->lineItems->removeElement($lineItem);
            // set the owning side to null (unless already changed)
            if ($lineItem->getOrders() === $this) {
                $lineItem->setOrders(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/shopping_cart/index.html.twig
{% extends 'base.html.twig' %} {% block title %}Santa Clothes {% endblock %} {% block body %} {# {#
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> {# #} {#
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> #} {# #} {#
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> #}


    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"> {% if app.user %}

        <div class="container mt-5">
        <div class="card shopping-cart">

            <div class="card-body">
                <!-- PRODUCT -->
                {% for item in app.user.lineItems %}
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-2 text-center ">
                            <img class="img-responsive" src="{{ asset( item.product.image ) }}" alt="prewiew" width="120" height="80">
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6 ">
                            <h5 class="product-name"><strong>{{item.product.name}}</strong></h5>
                            <h5>
                                <small class="text-muted">{{item.product.type}}</small>
                            </h5>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-3 text-md-right" style="padding-top: 5px">
                                <h6><strong>P.U : {{item.product.price}}<span class="text-muted"> €</span></strong></h6>
                            </div>
                            <div class="col-3 col-sm-3 col-md-3">
                                <div class="quantity">
                                    <input type="number" class="form-control text-center lineItem-quantity"
                                           min="1" max="{{ item.product.stock + item.quantity}}" data-item="{{ item.id }}"
                                           value="{{item.quantity}}" data-path="{{ path('update_quantity', {id: item.id}) }}">
                                </div>
                            </div>
                            <div class="col-3 col-sm-3 col-md-3 text-md-right" style="padding-top: 5px">
                                <h6><strong>P.T : <span class="total{{ item.id }} text-dark">{{item.price|round(2)}}</span><span class="text-muted"> €</span></strong></h6>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <a href="{{path('delete_line', {user: app.user.id, id: item.id})}}">
                                    <button type="button" class="btn btn-outline-danger btn-xs">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>


                    <hr> {% endfor %}
                <!-- END PRODUCT -->

            </div>
            <div>
                <div class="pull-right mb-2">
                        <h4 class="text-dark">TOTAL : <span class="total-price text-dark">{{ total }}</span> €</h4>
                </div>

            </div>
            <div class="pull-right mb-3">
                <a href=" {{path( 'checkout_shopping_cart')}} " class="btn btn-success col-12 col-md-3 pull-right mb-3 ">Valider le panier ></a>
                <a href="{{path('index')}}" class="btn btn-primary col-12 col-md-3">
                    < Poursuivre les achats </a>

            </div>


        </div>
    {% endif %} {% endblock %}

templates/shopping_cart/pay.html.twig
{% extends "shopping_cart/sidebar.html.twig" %} 

{% block paiement %}
<style>
    #recap {
        display: none;
    }
    *{
        text-align: center;
    }
    .wrapper{
        text-align: center;
      }
     #row1 , #row2{
         visibility: hidden;
     } 
</style>
        
    <div class="wrapper">
        <p> Votre numéro de carte : ************* </p>
        <p> Votre Nom sur la carte : Mme / Mr *********</p>
        <p> Code de sécurité : ***</p>
        <p> Date d'expiration : 12/23</p>
        <p> Vous voulez changer votre carte ? clicquer ici.</p>
        <a href="{{ path('address_validate')}}" class="btn btn-dark"> <--Addresse</a>

        <a href="{{path('confirm_order')}}" class="btn btn-dark">Validez</a>
    
    </div>
    <script>

        document.getElementBy('row1').style.display ="none";
        
        document.getElementById('paiement').classList.add('active');

    </script>
 
{% endblock paiement %}

templates/shopping_cart/sidebar.html.twig
{% extends 'base.html.twig' %} {% block title %}Santa clothes!{% endblock %}
{%block body %}
    <style>
        .wrapper{
            text-align: center;
        }
        #maDiv{
            background: -webkit-linear-gradient(left, #4840b6, #00c6ff);
        }
        .recap{
            color: white;
        }
    </style>
    <div class="container-fluid">
        <div class="row"></div>
        <div class="col-12"></div>
        <nav class="navbar navbar-expand navbar-light bg-light ">
            <div id="maDiv"  class="collapse navbar-collapse justify-content-center">
                <ul class="navbar-nav container">
                    <li id="recap" class="nav-item active col-4" style="display: block;">
                        <a class="nav-link" href="#"> <span>Récapulatif</span> <span class="sr-only">(current)</span></a>
                        <div id="row1" class="row">
                            <div class="recap" >
                                {% for lineItem in app.user.lineItems %}
                                    <p>{{ lineItem.product.name }} - {{ lineItem.price }} €</p>
                                {% endfor %}
                                {% if total is defined %}
                                    <p>TOTAL : {{ total }} €</p>
                                    {% elseif order is defined %}
                                    <p>TOTAL : {{ order.total }} €</p>
                                {% endif %}
                                <h5 class="card-title">Infos personnelle</h5>
                                <p> {{ app.user.firstName }} {{ app.user.lastName }}</p>
                                <p>email: {{ app.user.email }}</p>
                                <div class="wrapper">
                                    <a href="{{ path('address_validate')}}"
                                       class="btn btn-dark ">Validez --> </a>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li id="addressValidator" class="nav-item col-4 ">
                        <a class="nav-link" href="#"> <span> Vérification de l'addresse de livraison </span></a>
                        <div id="row2" class="row">
                            <div class="addressValidator">

                                {% block address %}

                                {% endblock address %}
                            </div>
                        </div>
                    </li>

                    <li id="paiement" class="nav-item col-4">
                        <a class="nav-link" href="#"> <span>Paiement </span> </a>
                        <div class="row">
                            <div class="paiement">

                                {% block  paiement %}

                                {% endblock paiement %}
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    </div>
    </div>
{% endblock %}

templates/shopping_cart/validate-address.html.twig
{% extends "shopping_cart/sidebar.html.twig" %} 

{% block address %}
<style>
    #recap{
        display: none;
    }
    *{
        text-align: center;
    }
    .wrapper{
        text-align: center;
      }
      p ,a {
          color: white;
      }
</style>
    {% if app.user.address %}

    {% for key in app.user.address %}
      <p>{{key.streetNumber}} , {{key.street}}</p>
      <p>{{key.city}} , {{key.country}} ,{{key.zipCode}} </p>
      <a href="{{path('address')}}">Vous voulez changer votre addresse de livraison ? <br> Cliquer ici.</a> <br>

        {% endfor %}

        <p> Vous n'avez pas encore rempli le formulaire d'addresse de livraison!</p><br>
    <a href="{{path('address')}}">Veuillez cliquez ici pour remplir le formulaire.</a> <br>
    {% endif %}
    <br>    
    
    <div class="wrapper">
        <a href="{{ path('checkout_shopping_cart')}}" class="btn btn-dark"> <-- Récapulatif</a>
        <a href="{{path('cart_pay')}}" class="btn btn-dark">Validez --></a>
    </div>

    <script>
        document.getElementById('row1').style.visibility ="hidden";
        document.getElementById('addressValidator').classList.add('active');
    </script>
 
{% endblock address %}